export const CLOSE_TIME = "closing time";
export const INSTRUCTIONS = "how to claim";
export const MARCUS_SOURCE_URL = "marcus source url";
export const NAME = "provider name";
export const OFFERS = "offer description";
export const OFFER_DAYS = "offer days";
export const OPEN_TIME = "opening time";
export const PROVIDER_SOURCE_URL = "provider source url";
export const URL = "provider url";
